ci:
  autofix_commit_msg: 'chore: auto fixes from pre-commit hooks'
  autofix_prs: false
  autoupdate_commit_msg: 'chore: pre-commit autoupdate'
  autoupdate_schedule: weekly
  skip: [conventional-pre-commit]
default_install_hook_types: [pre-commit, commit-msg]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-toml
      - id: detect-private-key
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: no-commit-to-branch
        args: [ --branch, master ]
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v4.0.0
    hooks:
      - id: add-trailing-comma
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.15.17'
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix ]
      - id: ruff-format
  - repo: https://github.com/pappasam/toml-sort
    rev: v0.24.4
    hooks:
      - id: toml-sort
        entry: toml-sort
        args: [ pyproject.toml ]
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [build, chore, ci, docs, feat, fix, perf, refactor, revert, style, test]
